### ISSUE TITLE
Insert select text into gitmoji's prompt

### ISSUE THREAD

**Issue by dcaixinha** [janusvm/emacs-gitmoji#3]
Hi! First of all, thanks for this great package :pray:

In order to speed-up the workflow of using gitmoji, I think it'd be great if we could insert whatever text the user has selected into the gitmoji prompt. The use-case would be that we can write a commit message (or a draft version), and then select part of it to auto-complete the gitmoji buffer prompt. WDYT?

**Comment by janusvm** [comment]
I think that's a great idea! It doesn't clash with the usual workflow either, so I'll look into adding it when I get the time :)
